# Dynamic path resolution to support both host execution and container environments
from pathlib import Path
import sys
import os
from dotenv import load_dotenv

current_dir = Path(__file__).resolve().parent
repo_root = current_dir
for parent in [current_dir] + list(current_dir.parents):
    if (parent / '.env').exists() or (parent / '.env.template.txt').exists():
        repo_root = parent
        break

# Add backend directory to sys.path
if (repo_root / 'backend').exists():
    sys.path.append(str(repo_root / 'backend'))
else:
    sys.path.append(str(repo_root))

# Add current scripts directory for local module imports
sys.path.append(str(current_dir))

if os.path.exists('/data'):
    data_dir = Path('/data')
else:
    data_dir = repo_root / 'data'

load_dotenv(dotenv_path=repo_root / '.env')

from pg_utils import PGUtils
from psycopg2 import sql

def fix_identity_columns():
    """
    Ensures all primary key 'id' columns are defined as IDENTITY 
    and that their sequences are synchronized with the existing data.
    """
    conn = PGUtils.get_connection()
    try:
        with conn.cursor() as cur:
            # 1. Find all tables in public and labeling schemas
            cur.execute("""
                SELECT table_schema, table_name 
                FROM information_schema.tables 
                WHERE table_schema IN ('public', 'labeling') 
                  AND table_type = 'BASE TABLE'
            """)
            tables = cur.fetchall()
            
            print(f"Checking {len(tables)} tables for identity columns...")
            
            for table in tables:
                schema = table['table_schema']
                name = table['table_name']
                
                # Check if table has an 'id' column (case insensitive)
                cur.execute(
                    sql.SQL("""
                        SELECT column_name, data_type, is_identity, column_default
                        FROM information_schema.columns
                        WHERE table_schema = %s AND table_name = %s
                          AND (column_name = 'id' OR column_name = 'ID')
                    """),
                    (schema, name)
                )
                col = cur.fetchone()
                
                if not col:
                    continue
                
                col_name = col['column_name']
                is_identity = col['is_identity'] == 'YES'
                has_default = col['column_default'] is not None
                
                print(f"Processing {schema}.{name}.{col_name}...")
                
                # 2. Convert to IDENTITY if it's not already
                if not is_identity:
                    try:
                        # If it has a default (like from SERIAL), drop it first to avoid conflicts
                        if has_default:
                            cur.execute(
                                sql.SQL("ALTER TABLE {schema}.{table} ALTER COLUMN {col} DROP DEFAULT").format(
                                    schema=sql.Identifier(schema),
                                    table=sql.Identifier(name),
                                    col=sql.Identifier(col_name)
                                )
                            )
                        
                        # Set NOT NULL (required for identity)
                        cur.execute(
                            sql.SQL("ALTER TABLE {schema}.{table} ALTER COLUMN {col} SET NOT NULL").format(
                                schema=sql.Identifier(schema),
                                table=sql.Identifier(name),
                                col=sql.Identifier(col_name)
                            )
                        )
                        
                        # Add IDENTITY
                        cur.execute(
                            sql.SQL("ALTER TABLE {schema}.{table} ALTER COLUMN {col} ADD GENERATED BY DEFAULT AS IDENTITY").format(
                                schema=sql.Identifier(schema),
                                table=sql.Identifier(name),
                                col=sql.Identifier(col_name)
                            )
                        )
                        print(f"  [+] Successfully converted to IDENTITY.")
                    except Exception as e:
                        print(f"  [!] Failed to convert {schema}.{name}.{col_name}: {e}")
                        conn.rollback()
                        continue # Move to next table
                
                # 3. Synchronize Sequence
                try:
                    cur.execute(
                        sql.SQL("SELECT MAX({col}) FROM {schema}.{table}").format(
                            schema=sql.Identifier(schema),
                            table=sql.Identifier(name),
                            col=sql.Identifier(col_name)
                        )
                    )
                    max_id = cur.fetchone()['max']
                    
                    if max_id is not None:
                        # For identity columns, we use pg_get_serial_sequence
                        cur.execute(
                            sql.SQL("SELECT setval(pg_get_serial_sequence(%s, %s), %s)").format(),
                            (f"{schema}.{name}", col_name, max_id)
                        )
                        print(f"  [ok] Sequence synced to {max_id}.")
                except Exception as e:
                    print(f"  [!] Sequence sync failed for {schema}.{name}: {e}")
                    conn.rollback()

            conn.commit()
            print("\nIdentity and sequence synchronization complete.")
            
    except Exception as e:
        print(f"Error: {e}")
        conn.rollback()
    finally:
        conn.close()

if __name__ == "__main__":
    fix_identity_columns()