"""Add faers count fields to ProjectAeReportDetail

Revision ID: cbaf12977b82
Revises: 41e1e18194c9
Create Date: 2026-02-25 12:59:51.193758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbaf12977b82'
down_revision = '41e1e18194c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('brand_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('manufacturer_name',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('project_ae_report_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faers_1yr_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('faers_5yr_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_ae_report_detail', schema=None) as batch_op:
        batch_op.drop_column('faers_5yr_count')
        batch_op.drop_column('faers_1yr_count')

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('manufacturer_name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('brand_name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
